# Site title
title: "Building Powerful Community Organizations"

# Building Powerful Community Organizations
bpco_title: "Building Powerful Community Organizations"
bpco_site: "http://buildingpowerfulcommunityorganizations.com/"
bpco_book: "https://www.amazon.com/Building-Powerful-Community-Organizations-Personal/dp/0977151808/"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: <USERNAME>/<PROJECT>

# How to contact us.
email: "gvwilson@third-bit.com"

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..

# Specify that exercises should be output.
collections:
  exercises:
    output: true
    permalink: /:path/

# Order of exercises.
order:
  - "/putting-your-vision-into-words/"
  - "/finding-the-stories-that-guide-you/"
  - "/looking-into-yourself-is-the-first-step-of-a-good-leader/"
  - "/finding-your-core-beliefs/"

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin
